language: ruby
rvm:
- 2.3.0
script:
- bundle exec rake db:migrate --trace
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec -fd spec/
deploy:
  provider: heroku
  api_key:
    secure: f9BLOyigjYbQC3QW3CMik+FMSFDe2WkQfnW41Srxxqy8Kf67RVsvPr0pJDVantefpdXxHY8FdPE8G2NcCEX7bTv+pZ+IY7O/ScMQ6iq+wxHPZkCuLfSEiMvNQdew0qxlKKwGUH7MUwZ+zeEAUR1BHee5fvxo7sqSmUl8Qm14flC153a4ShjrO44Ck1H3IQJs/lOFsJDc6BFUATOJtNDzoYWbBcnzNVcHHy/ZePoJPFVocKU0F06GrZeGV+2mAspCucs4XTE1gupHSgT8V8mzxN+GZ+34XiV82uws/DT5DgXCjLoLu0lltP9tPyYcfjGu+iJSuDU+w5zg3Anoz8jw1tinrmncXH8VBAcqeEf2MootIAODgGYAKVj0tjfXETxfSMm6zPmo+SMn3RKOXj940MM+AxrIZkvyth6FeKQA3o9vobbZ0J5t67w7I47IYYU8wgfdBht+2bSuyKfeN0KxlFC+fHXdUavhRXWQnIBn+tIKqMdK/I8afCcFFoWiPQXhlU9QzbuEW3ID563odXsM0FwwZcP2bMPT1Zpug7Hxb6N8u8bySca9OYOCnI0x/XJBiPlyxwep8a73+xUP8Rjn/7WtZ+JhcFNBF2vsR6tXUnNxoYNXe101IdTUJasIzHxBPG+zj8tfqRjSee5NfuEy8xDfq+I9r5r/1LoaK6pvPlc=
  app: enigmatic-forest-9635
  on:
    repo: emivo/wadror
